name: Publish image

on:
  workflow_dispatch:
    inputs:
      gum_version:
        description: What version of gum should be used?
        default: '0.9.0'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: BuildX Create
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        build-args: |
          GUM_VERSION=${{ github.event.inputs.gum_version }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: |
          jdcmarques/gum:latest
          jdcmarques/gum:${{ github.event.inputs.gum_version }}
